[mypy]
python_version = 3.12
strict = true
ignore_missing_imports = true
plugins = pydantic.mypy

[mypy-alembic.*]
ignore_missing_imports = true

[mypy-apscheduler.*]
ignore_missing_imports = true

[mypy-imagehash.*]
ignore_missing_imports = true
